baseurl      = "https://rachelsohzc.github.io/portfolio/"
title        = "Rachel Soh"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to my portfolio!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My portfolio"
  keywords = "homepage, portfolio"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Rachel Soh"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Portfolio"

    [languages.en.params.logo]
      logoText = "Rachel Soh"
      logoHomeLink = "https://rachelsohzc.github.io/portfolio/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[[params.social]]

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/rachelsohzc/"

    [[params.social]]
      name = "github"
      url  = "https://github.com/rachelsohzc"

    [[params.social]]
      name = "email"
      url  = "mailto:rachelsohzc@gmail.com"


  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight = 2

  [[menu.main]]
    identifier = "CV"
    name       = "CV"
    url        = "https://docs.google.com/document/d/1q-szLP_Kas7zyNlrrNavxVqQbMpRIu6EzwwJUmb4maI/edit?usp=sharing"
    weight = 3
